default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sample1_development

test:
  <<: *default
  database: sample1_test

production:
  <<: *default
  database: sample1_production
  username: sample1
  password: <%= ENV['SAMPLE1_DATABASE_PASSWORD'] %>
